api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    version: '1.0.0'

    # The title of the API.
    title: 'Adviqo API'

    # The description of the API.
    description: 'The current version offers access to the adviser resources.'

    show_webby: false


